config/routes.rb
Rails.application.routes.draw do
  root 'games#dashboard'
  resources :students, only: [:index]
  get "/students-first", to: "students#index_first"
  get "/students-second", to: "students#index_second"
  get "/students-third", to: "students#index_third"

  resources :games
  get "/games-first/new", to: "games#new_first", as: "new_first_game"
  get "/games-second/new", to: "games#new_second", as: "new_second_game"
  get "/games-third/new", to: "games#new_third", as: "new_third_game"

  get "/dashboard", to: "games#dashboard", as: "dashboard"
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  belongs_to :student
end

app/models/game.rb
class Game < ActiveRecord::Base

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :facts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.order("score DESC").limit(20)
  end

  def dashboard
  end

  def new
    @game = Game.new;
  end

  def new_first
    @game = Game.new;
  end

  def new_second
    @game = Game.new;
  end

  def new_third
    @game = Game.new;
  end

  def create
    @game = Game.create!(game_params)
    redirect_to games_path
  end

  private
    def game_params
      params.require(:game).permit(:name, :score, :game_type)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    render json: Student.all
  end

  def index_first
    render json: Student.where(year: '1')
  end

  def index_second
    render json: Student.where(year: '2')
  end

  def index_third
    render json: Student.where(year: '3')
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_submit_game.html.erb
<%= form_for(@game) do |f| %>
    <div class="form-group">
        <%= label_tag(:name) %>
        <%= f.text_field :name, :class => 'form-control', :required => true, :placeholder => 'Enter Name', :type => 'text'  %>
    </div>
    <div class="form-group">
        <%= label_tag(:score, "Your Score") %>
        <%= f.hidden_field(:score, onchange: "alert('Input collected!')") %>
        <p id="submittedScore"></p>
    </div>
    <div class="form-group">
        <%= label_tag(:game_type, "Game Type") %>
        <%= f.hidden_field(:game_type, value: "All Scholars", onchange: "alert('Input collected!')") %>
        <p>All Students</p>
    </div>
    <%= f.submit "Submit", :class => 'btn btn-primary block m-b' %>
<% end %>

app/views/games/_submit_game_first.html.erb
<%= form_for(@game) do |f| %>
    <div class="form-group">
        <%= label_tag(:name) %>
        <%= f.text_field :name, :class => 'form-control', :required => true, :placeholder => 'Enter Name', :type => 'text'  %>
    </div>
    <div class="form-group">
        <%= label_tag(:score, "Your Score") %>
        <%= f.hidden_field(:score, onchange: "alert('Input collected!')") %>
        <p id="submittedScore"></p>
    </div>
    <div class="form-group">
        <%= label_tag(:game_type, "Game Type") %>
        <%= f.hidden_field(:game_type, value: "First Years", onchange: "alert('Input collected!')") %>
        <p>First Years</p>
    </div>
    <%= f.submit "Submit", :class => 'btn btn-primary block m-b' %>
<% end %>

app/views/games/_submit_game_second.html.erb
<%= form_for(@game) do |f| %>
    <div class="form-group">
        <%= label_tag(:name) %>
        <%= f.text_field :name, :class => 'form-control', :required => true, :placeholder => 'Enter Name', :type => 'text'  %>
    </div>
    <div class="form-group">
        <%= label_tag(:score, "Your Score") %>
        <%= f.hidden_field(:score, onchange: "alert('Input collected!')") %>
        <p id="submittedScore"></p>
    </div>
    <div class="form-group">
        <%= label_tag(:game_type, "Game Type") %>
        <%= f.hidden_field(:game_type, value: "Second Years", onchange: "alert('Input collected!')") %>
        <p>Second Years</p>
    </div>
    <%= f.submit "Submit", :class => 'btn btn-primary block m-b' %>
<% end %>

app/views/games/_submit_game_third.html.erb
<%= form_for(@game) do |f| %>
    <div class="form-group">
        <%= label_tag(:name) %>
        <%= f.text_field :name, :class => 'form-control', :required => true, :placeholder => 'Enter Name', :type => 'text'  %>
    </div>
    <div class="form-group">
        <%= label_tag(:score, "Your Score") %>
        <%= f.hidden_field(:score, onchange: "alert('Input collected!')") %>
        <p id="submittedScore"></p>
    </div>
    <div class="form-group">
        <%= label_tag(:game_type, "Game Type") %>
        <%= f.hidden_field(:game_type, value: "Third+ Years", onchange: "alert('Input collected!')") %>
        <p>Third+ Years</p>
    </div>
    <%= f.submit "Submit", :class => 'btn btn-primary block m-b' %>
<% end %>

app/views/games/dashboard.html.erb
<div class="wrapper wrapper-content">
    <div class="row animated fadeInLeft">
        <div class="col-lg-6 text-center">
            <div class="ibox">
              <div class="ibox-title">
                <h1><strong>Can You Name Scholars in Oxford?</strong></h1>
              </div>
              <div class="ibox-content" style="height:425px">
                  <%= image_tag "rhodes_hall_circle.png", width: "30%", style:"margin:20px 0;"%>
                    <h3 style="margin:10px">Choose scholars based on photos.</h3>
                    <button class="btn btn-primary dim" style="margin:10px"><%= link_to 'First Years', new_first_game_path, style:"color:#fff" %></button>
                    <button class="btn btn-primary dim" style="margin:10px"><%= link_to 'Second Years', new_second_game_path, style:"color:#fff" %></button>
                    <button class="btn btn-primary dim" style="margin:10px"><%= link_to 'Third+ Years', new_third_game_path, style:"color:#fff" %></button>
                    <button class="btn btn-primary dim" style="margin:10px"><%= link_to 'All Scholars in Oxford', new_game_path, style:"color:#fff" %></button>
              </div>
            </div>
        </div>
        <div class="col-lg-6 text-center">
            <div class="ibox">
              <div class="ibox-title">
                <h1><strong>Do You Know Scholars in Oxford?</strong></h1>
              </div>
              <div class="ibox-content" style="height:425px">
                  <%= image_tag "rhodes_lecture_circle.png", width: "30%", style:"margin:20px 0;" %>
                  <h3 style="margin:10px"><br>Choose classmates based on personal facts from Facebook.<br>Can also submit facts about each other.</h3>
                  <h3 style="font-size:18px;"><br>Coming Soon</h3>
              </div>
            </div>
        </div>
    </div>
</div>

app/views/games/index.html.erb
<div class="wrapper wrapper-content">
<div class="row animated fadeInLeft text-center">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="ibox-title">
      <h1><i class="fa fa-trophy modal-icon"></i> High Scores</h1>
    </div>
    <div class="ibox-content">
      <table class="footable table table-stripped default footable-loaded" data-page-size="8" data-filter="#filter" >
          <thead>
            <tr>
                <th class="footable-visible footable-first-column footable-sortable text-center">Name</th>
                <th class="footable-visible footable-sortable text-center">Score</th>
                <th class="footable-visible footable-sortable text-center">Game Type</th>
                <th data-hide="phone,tablet" class="footable-visible footable-last-column footable-sortable text-center">Date & Time</th>
            </tr>
          </thead>
          <tbody>
            <% for game in @games %>
              <tr class="gradeX footable-even" style="display: table-row;">
                <td class="footable-visible footable-first-column"><span class="footable-toggle"></span><strong><%= game.name %></strong></td>
                <td class="footable-visible"><span class="footable-toggle"></span><%= game.score %></td>
                <td class="footable-visible"><span class="footable-toggle"></span><%= game.game_type %></td>
                <td class="center footable-visible footable-last-column"><span class="footable-toggle"></span><%= game.created_at.strftime("%d/%m/%Y") %>, <%= game.created_at.strftime("%I:%M%p") %></td>
              </tr>
            <% end %>
           </tbody>
           <tfoot>
          <tr>
              <td colspan="8" class="footable-visible">
              </td>
          </tr>
          </tfoot>
      </table>
    </div>
  </div>
</div>
</div>

app/views/games/new.html.erb
<div class="wrapper wrapper-content">
<div class="row animated fadeInLeft">
  <div class="col-md-8 col-md-offset-2 text-center">
    <div class="ibox-title">
      <div class="row">
        <div class="col-sm-4 text-left">
          <h3 class="btn dim"><strong>Your Score: <span id="score">0</span></strong></h3>
        </div>
        <div class="col-sm-4 col-sm-offset-4 text-right">
          <button id="submitScore" class="btn" data-toggle="modal" data-target="#submitModal" style="margin-bottom:0"><h3 style="margin-bottom:5px;"><i class="fa fa-check-square"></i> Submit Score</h3></button>
        </div>
      </div>
      <h1><strong>Who is pictured below?</strong></h1>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
          <img id="photo" class="img-responsive img-center" style="max-height:200px;margin-top:15px;margin-bottom:25px;" />
        </div>
      </div>
      <div class="row">
        <button id="0" class="btn btn-primary block m-b ans inline dim"></button>
        <button id="1" class="btn btn-primary block m-b ans inline dim"></button>
        <button id="2" class="btn btn-primary block m-b ans inline dim"></button>
        <button id="3" class="btn btn-primary block m-b ans inline dim"></button>
      </div>
      <div class="row animated fadeInLeft">
        <div class="col-sm-6 col-sm-offset-3">
          <div id="responseMessage"></div>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-sm-12">
          <button class="btn" id="next" style="display:none;margin-bottom:10px;"> Next <i class="fa fa-chevron-right"></i></button>
        </div>
      </div>
      <div class="row text-right">
      </div>
    </div>
    <div class="modal inmodal" id="submitModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content animated fadeIn">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cancel</span></button>
                  <i class="fa fa-trophy modal-icon"></i>
                  <h4 class="modal-title">Submit Score</h4>
              </div>
              <div class="modal-body" style="max-height: 350px; overflow-y: auto;">
                  <%= render 'submit_game' %>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
<script type="text/javascript">
$(document).ready(function() {

  //Add Shuffle Function to Array class
  Array.prototype.shuffle = function() {
    var input = this;
    for (var i = input.length-1; i >=0; i--) {
        var randomIndex = Math.floor(Math.random()*(i+1));
        var itemAtIndex = input[randomIndex];
        input[randomIndex] = input[i];
        input[i] = itemAtIndex;
    }
    return input;
  }

  //Student Model
  Student = function(name,facebookID,photoURL) {
    this.name = name;
    this.facebookID = facebookID;
    this.photoURL = photoURL;
    this.chosen = false;
  }

  //Game Model
  Game = function() {
    this.allStudents = []
    this.remainingStudents = [];
    this.photoURL = "";
    this.score = 0;
  }

  Game.prototype = {
    start: function() {
      //Seed all students
      $.ajax({
        method: "GET",
        url: "/students",
        dataType: "json"
      }).done(function(studentsJsonArray) {
          console.log("Response successful")
          console.log(studentsJsonArray)
          this.createStudents(studentsJsonArray);
          this.renderQuestion();
      }.bind(this));
      //Listener & actions on Next Button
      $("#next").click(function(e){
        $("#responseMessage").html("")
        this.renderQuestion();
        $("#next").hide();
      }.bind(this));
      //Listener & actions on End & Save Button
      $("#submitScore").click(function(e){
        $("#submittedScore").html(this.score)
      }.bind(this));
      //Listener on Submit Score Form
      $('form').submit(function() {
        console.log(this.score)
        $("#game_score").val(this.score);
        return true;
      }.bind(this));
    },
    createStudents: function(studentsJsonArray) {
      for(var i=1;i<studentsJsonArray.length;i++) {
      this.allStudents.push(new Student(studentsJsonArray[i].name,studentsJsonArray[i].facebook_id,studentsJsonArray[i].photo_url));
     }
     console.log(this.allStudents)
     this.remainingStudents = this.allStudents;
    },
    getStudentChoices: function(count) {
      var studentChoices =[];
      var studentIndexes =[];
      //Get Chosen Student
      var chosenStudentIndex = Math.floor(Math.random()*this.remainingStudents.length);
      var chosenStudent = this.remainingStudents[chosenStudentIndex];
      chosenStudent.chosen = true;
      this.remainingStudents.splice(chosenStudentIndex, 1);
      studentChoices.push(chosenStudent);
      studentIndexes.push(chosenStudentIndex);
      //Get Other Students
      var totalStudentsCount = this.allStudents.length;
      while(studentIndexes.length < count){
        var index=Math.floor(Math.random()*totalStudentsCount);
        var alreadyChosen=false;
        for(var i=0;i<studentIndexes.length;i++) {
          if(studentIndexes[i]==index){alreadyChosen=true;break}
        }
        if(!alreadyChosen) {
          studentIndexes.push(index);
          studentChoices.push(this.allStudents[index]);
        }
      }
      return studentChoices;
    },
    renderQuestion: function() {
      var studentChoices = this.getStudentChoices(4);
      var chosenStudent = studentChoices[0];
      studentChoices.shuffle();
      $('#0').html(studentChoices[0].name);
      $('#1').html(studentChoices[1].name);
      $('#2').html(studentChoices[2].name);
      $('#3').html(studentChoices[3].name);
      $('#photo').attr("src","/assets/photos/"+chosenStudent.photoURL);

      //Add Listeners to Answer Choices & specify if correct/incorrect when clicked
      $(".ans").click(function(e){
        var clickedId = e.target.id;
        if(studentChoices[Number(clickedId)].chosen == true) {
          $("#responseMessage").html('<div class="alert alert-success alert-dismissable" style="margin-bottom:10px;">Correct.</div>');
          this.score = this.score+1;
          console.log(this.score);
          $("#score").html(this.score);
          $("#next").show();
        } else {
          $("#responseMessage").html('<div id="incorrect" class="alert alert-danger alert-dismissable" style="margin-bottom:10px;">Incorrect. The correct answer is '+chosenStudent.name+'</div>');
          $("#next").show();
        }
        $(".ans").unbind("click");
      }.bind(this));
    }
  }

  // Start Game (Refactor ToDos: (1) divide functions into Game Controller & Game Model. (2) move code into asset pipeline)
  var game = new Game()
  game.start()

});
</script>

app/views/games/new_first.html.erb
<div class="wrapper wrapper-content">
<div class="row animated fadeInLeft">
  <div class="col-md-8 col-md-offset-2 text-center">
    <div class="ibox-title">
      <div class="row">
        <div class="col-sm-4 text-left">
          <h3 class="btn dim"><strong>Your Score: <span id="score">0</span></strong></h3>
        </div>
        <div class="col-sm-4 col-sm-offset-4 text-right">
          <button id="submitScore" class="btn" data-toggle="modal" data-target="#submitModal" style="margin-bottom:0"><h3 style="margin-bottom:5px;"><i class="fa fa-check-square"></i> Submit Score</h3></button>
        </div>
      </div>
      <h1><strong>Who is pictured below?</strong></h1>
      <div class="row text-center">
        <div class="col-xs-4 col-xs-offset-4">
          <img id="photo" class="img-responsive img-center" style="max-height:200px;margin-top:15px;margin-bottom:25px;" />
        </div>
      </div>
      <div class="row">
        <button id="0" class="btn btn-primary block m-b ans inline dim"></button>
        <button id="1" class="btn btn-primary block m-b ans inline dim"></button>
        <button id="2" class="btn btn-primary block m-b ans inline dim"></button>
        <button id="3" class="btn btn-primary block m-b ans inline dim"></button>
      </div>
      <div class="row animated fadeInLeft">
        <div class="col-sm-6 col-sm-offset-3">
          <div id="responseMessage"></div>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-sm-12">
          <button class="btn" id="next" style="display:none;margin-bottom:10px;"> Next <i class="fa fa-chevron-right"></i></button>
        </div>
      </div>
      <div class="row text-right">
      </div>
    </div>
    <div class="modal inmodal" id="submitModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content animated fadeIn">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cancel</span></button>
                  <i class="fa fa-trophy modal-icon"></i>
                  <h4 class="modal-title">Submit Score</h4>
              </div>
              <div class="modal-body" style="max-height: 350px; overflow-y: auto;">
                  <%= render 'submit_game_first' %>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
<script type="text/javascript">
$(document).ready(function() {

  //Add Shuffle Function to Array class
  Array.prototype.shuffle = function() {
    var input = this;
    for (var i = input.length-1; i >=0; i--) {
        var randomIndex = Math.floor(Math.random()*(i+1));
        var itemAtIndex = input[randomIndex];
        input[randomIndex] = input[i];
        input[i] = itemAtIndex;
    }
    return input;
  }

  //Student Model
  Student = function(name,facebookID,photoURL) {
    this.name = name;
    this.facebookID = facebookID;
    this.photoURL = photoURL;
    this.chosen = false;
  }

  //Game Model
  Game = function() {
    this.allStudents = []
    this.remainingStudents = [];
    this.photoURL = "";
    this.score = 0;
  }

  Game.prototype = {
    start: function() {
      //Seed all students
      $.ajax({
        method: "GET",
        url: "/students-first",
        dataType: "json"
      }).done(function(studentsJsonArray) {
          console.log("Response successful")
          console.log(studentsJsonArray)
          this.createStudents(studentsJsonArray);
          this.renderQuestion();
      }.bind(this));
      //Listener & actions on Next Button
      $("#next").click(function(e){
        $("#responseMessage").html("")
        this.renderQuestion();
        $("#next").hide();
      }.bind(this));
      //Listener & actions on End & Save Button
      $("#submitScore").click(function(e){
        $("#submittedScore").html(this.score)
      }.bind(this));
      //Listener on Submit Score Form
      $('form').submit(function() {
        console.log(this.score)
        $("#game_score").val(this.score);
        return true;
      }.bind(this));
    },
    createStudents: function(studentsJsonArray) {
      for(var i=1;i<studentsJsonArray.length;i++) {
      this.allStudents.push(new Student(studentsJsonArray[i].name,studentsJsonArray[i].facebook_id,studentsJsonArray[i].photo_url));
     }
     console.log(this.allStudents)
     this.remainingStudents = this.allStudents;
    },
    getStudentChoices: function(count) {
      var studentChoices =[];
      var studentIndexes =[];
      //Get Chosen Student
      var chosenStudentIndex = Math.floor(Math.random()*this.remainingStudents.length);
      var chosenStudent = this.remainingStudents[chosenStudentIndex];
      chosenStudent.chosen = true;
      this.remainingStudents.splice(chosenStudentIndex, 1);
      studentChoices.push(chosenStudent);
      studentIndexes.push(chosenStudentIndex);
      //Get Other Students
      var totalStudentsCount = this.allStudents.length;
      while(studentIndexes.length < count){
        var index=Math.floor(Math.random()*totalStudentsCount);
        var alreadyChosen=false;
        for(var i=0;i<studentIndexes.length;i++) {
          if(studentIndexes[i]==index){alreadyChosen=true;break}
        }
        if(!alreadyChosen) {
          studentIndexes.push(index);
          studentChoices.push(this.allStudents[index]);
        }
      }
      return studentChoices;
    },
    renderQuestion: function() {
      var studentChoices = this.getStudentChoices(4);
      var chosenStudent = studentChoices[0];
      studentChoices.shuffle();
      $('#0').html(studentChoices[0].name);
      $('#1').html(studentChoices[1].name);
      $('#2').html(studentChoices[2].name);
      $('#3').html(studentChoices[3].name);
      $('#photo').attr("src","/assets/photos/"+chosenStudent.photoURL);

      //Add Listeners to Answer Choices & specify if correct/incorrect when clicked
      $(".ans").click(function(e){
        var clickedId = e.target.id;
        if(studentChoices[Number(clickedId)].chosen == true) {
          $("#responseMessage").html('<div class="alert alert-success alert-dismissable" style="margin-bottom:10px;">Correct.</div>');
          this.score = this.score+1;
          console.log(this.score);
          $("#score").html(this.score);
          $("#next").show();
        } else {
          $("#responseMessage").html('<div id="incorrect" class="alert alert-danger alert-dismissable" style="margin-bottom:10px;">Incorrect. The correct answer is '+chosenStudent.name+'.</div>');
          $("#next").show();
        }
        $(".ans").unbind("click");
      }.bind(this));
    }
  }

  // Start Game (Refactor ToDos: (1) divide functions into Game Controller & Game Model. (2) move code into asset pipeline)
  var game = new Game()
  game.start()

});
</script>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div  class="pull-right">
        <a href="https://www.linkedin.com/company/5357952" style="color:#676a6c"><strong>Melissa McCoy</strong></a> &copy; 2015-2016
    </div>
</div>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <i class="fa fa-reorder"></i>
            </button>
            <a href="/" class="navbar-brand" style="padding:15px;width:250px;"><%= image_tag "logo2.png", width:"100%" %></a>

        </div>
        <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-top-links navbar-right" >
            <li><a href="<%= url_for dashboard_path %>" ><i class="fa fa-gamepad"></i>New Game</a></li>
            <li><a href="<%= url_for games_path %>" ><i class="fa fa-trophy"></i>High Scores</a></li>
        </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Rhodes 2015 Name-That-Scholar Quiz Game">
    <meta name="author" content="Melissa McCoy">
    <link rel="shortcut icon" href="/favicon.ico?v=2">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="initial-scale=1.0">
    <title>Rhodes 2015 Name-That-Scholar Quiz Game</title>

    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body class="top-navigation">

    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <%= render 'layouts/topnavbar' %>

            <%= yield %>

            <%= render 'layouts/footer' %>

        </div>

    </div>

    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
    <%= yield :javascript %>

</body>
</html>